import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/report_summary.dart';
import '../models/company_profile.dart';
import '../services/company_service.dart';

class PdfService {
  PdfService._();

  static Future<String?> generateExpenseReport({
    required List<Map<String, dynamic>> expenses,
    required String truckFilter,
    DateTime? fromDate,
    DateTime? toDate,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('yyyy-MM-dd');
    final dateTimeFormat = DateFormat('yyyy-MM-dd HH:mm');
    final unicodeFont = await _loadUnicodeFont();
    final totalAmount = expenses.fold<double>(
      0,
      (sum, expense) => sum + _parseAmount(expense['amount']),
    );
    final generatedOn = dateTimeFormat.format(DateTime.now());
    final companyProfile = await CompanyService.instance.getCompany();
    final logoImage = await _loadLogoImage(companyProfile.logoPath);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(18),
        build: (pw.Context context) {
          return [
            _buildHeader(logoImage, unicodeFont, companyProfile),
            pw.SizedBox(height: 12),

            pw.SizedBox(height: 14),
            _buildReportDetailsSection(
              truckFilter: truckFilter,
              fromDate: fromDate,
              toDate: toDate,
              generatedOn: generatedOn,
              dateFormat: dateFormat,
              unicodeFont: unicodeFont,
            ),
            pw.SizedBox(height: 12),
            _buildSummarySection(
              totalEntries: expenses.length,
              totalAmount: totalAmount,
              unicodeFont: unicodeFont,
            ),
            pw.SizedBox(height: 12),
            expenses.isEmpty
                ? pw.Center(
                    child: pw.Text(
                      'No expense records found.',
                      style: pw.TextStyle(font: unicodeFont, fontSize: 12),
                    ),
                  )
                : _buildExpenseTable(expenses, dateFormat, unicodeFont),
            pw.SizedBox(height: 12),
            _buildGrandTotalRow(
              totalAmount: totalAmount,
              unicodeFont: unicodeFont,
            ),
          ];
        },
        footer: (pw.Context context) {
          return pw.Container(
            margin: const pw.EdgeInsets.only(top: 8),
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                top: pw.BorderSide(
                  color: PdfColor.fromInt(0xFFD6D6D6),
                  width: 0.6,
                ),
              ),
            ),
            padding: const pw.EdgeInsets.only(top: 6),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'Generated by',
                      style: pw.TextStyle(
                        font: unicodeFont,
                        fontSize: 8,
                        color: PdfColors.grey700,
                      ),
                    ),
                    pw.Text(
                      companyProfile.companyName,
                      style: pw.TextStyle(
                        font: unicodeFont,
                        fontSize: 8,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ),
                pw.Text(
                  generatedOn,
                  style: pw.TextStyle(
                    font: unicodeFont,
                    fontSize: 8,
                    color: PdfColors.grey700,
                  ),
                ),
                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: pw.TextStyle(
                    font: unicodeFont,
                    fontSize: 8,
                    color: PdfColors.grey700,
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );


    try {
      final bytes = await pdf.save();
      final directory = await getTemporaryDirectory();
      final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
      final filePath = path.join(
        directory.path,
        'expense_report_$timestamp.pdf',
      );
      final file = File(filePath);
      await file.writeAsBytes(bytes, flush: true);
      return file.path;
    } catch (e) {
      debugPrint("PDF Save Error: $e");
      return null;
    }
  }

  static Future<String?> generateOperatingCostReport({
    required ReportSummary summary,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('yyyy-MM-dd');
    final dateTimeFormat = DateFormat('yyyy-MM-dd HH:mm');
    final unicodeFont = await _loadUnicodeFont();
    final generatedOn = dateTimeFormat.format(DateTime.now());
    final companyProfile = await CompanyService.instance.getCompany();
    final logoImage = await _loadLogoImage(companyProfile.logoPath);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(18),
        build: (pw.Context context) {
          return [
            _buildHeader(logoImage, unicodeFont, companyProfile),
            pw.SizedBox(height: 12),
            pw.Center(
              child: pw.Text(
                summary.truckCosts.length == 1
                  ? "TRUCK OPERATING COST REPORT: ${summary.truckCosts.first.truckNumber}"
                  : "FLEET OPERATING COST REPORT",
                style: pw.TextStyle(
                  font: unicodeFont,
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromInt(0xFF2E7D32),
                ),
              ),
            ),
            pw.SizedBox(height: 8),
            pw.Center(
              child: pw.Text(
                "Period: ${dateFormat.format(summary.startDate)} to ${dateFormat.format(summary.endDate)}",
                style: pw.TextStyle(font: unicodeFont, fontSize: 10),
              ),
            ),
            pw.SizedBox(height: 14),
            _buildOperatingSummarySection(summary, unicodeFont),
            pw.SizedBox(height: 14),
            pw.Text(
              "TRUCK-WISE BREAKDOWN",
              style: pw.TextStyle(
                font: unicodeFont,
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 8),
            _buildTruckCostTable(summary.truckCosts, unicodeFont),
          ];
        },
        footer: (pw.Context context) {
          return _buildFooter(context, generatedOn, unicodeFont, companyProfile);
        },
      ),
    );

    try {
      final bytes = await pdf.save();
      final directory = await getTemporaryDirectory();
      final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
      final filePath = path.join(
        directory.path,
        'operating_report_$timestamp.pdf',
      );
      final file = File(filePath);
      await file.writeAsBytes(bytes, flush: true);
      return file.path;
    } catch (e) {
      debugPrint("PDF Save Error: $e");
      return null;
    }
  }

  static pw.Widget _buildOperatingSummarySection(ReportSummary summary, pw.Font? font) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(width: 0.6, color: PdfColor.fromInt(0xFFD6D6D6)),
      ),
      child: pw.Column(
        children: [
          _buildSummaryRow("General Expenses", _formatCurrency(summary.expenseTotal), font),
          _buildSummaryRow("Fuel Cost", _formatCurrency(summary.fuelTotal), font),
          _buildSummaryRow("Maintenance Cost", _formatCurrency(summary.maintenanceTotal), font),
          pw.Divider(thickness: 0.5, color: PdfColor.fromInt(0xFFD6D6D6)),
          _buildSummaryRow("TOTAL OPERATING COST", _formatCurrency(summary.operatingCostTotal), font, isBold: true),
        ],
      ),
    );
  }

  static pw.Widget _buildSummaryRow(String label, String value, pw.Font? font, {bool isBold = false}) {
    final style = pw.TextStyle(
      font: font,
      fontSize: 10,
      fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal,
    );
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: style),
          pw.Text(value, style: style),
        ],
      ),
    );
  }

  static pw.Widget _buildTruckCostTable(List<TruckCostSummary> costs, pw.Font? font) {
    final headers = ['Truck No.', 'Expenses', 'Fuel', 'Maint.', 'Total'];
    final data = costs.map((c) => [
      c.truckNumber,
      _formatCurrency(c.expenseTotal),
      _formatCurrency(c.fuelTotal),
      _formatCurrency(c.maintenanceTotal),
      _formatCurrency(c.operatingCostTotal),
    ]).toList();

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: data,
      border: pw.TableBorder.all(width: 0.5, color: PdfColor.fromInt(0xFFD6D6D6)),
      headerStyle: pw.TextStyle(font: font, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: PdfColor.fromInt(0xFF2E7D32)),
      cellStyle: pw.TextStyle(font: font, fontSize: 9),
      cellAlignment: pw.Alignment.centerRight,
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(2),
        2: const pw.FlexColumnWidth(2),
        3: const pw.FlexColumnWidth(2),
        4: const pw.FlexColumnWidth(2),
      },
      headerAlignment: pw.Alignment.center,
    );
  }

  static pw.Widget _buildFooter(pw.Context context, String generatedOn, pw.Font? font, CompanyProfile profile) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColor.fromInt(0xFFD6D6D6), width: 0.6)),
      ),
      padding: const pw.EdgeInsets.only(top: 6),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('Generated by', style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey700)),
              pw.Text(profile.companyName, style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey700)),
            ],
          ),
          pw.Text(generatedOn, style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey700)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey700)),
        ],
      ),
    );
  }

  static pw.Widget _buildHeader(
    pw.MemoryImage? logoImage,
    pw.Font? unicodeFont,
    CompanyProfile profile,
  ) {
    final titleStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 22,
      fontWeight: pw.FontWeight.bold,
      color: PdfColor.fromHex("#2E7D32"),
    );

    final subtitleStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 11,
      color: PdfColors.grey700,
    );

    final companyStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 10,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.black,
    );

    final infoStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 9,
      color: PdfColors.grey700,
    );

    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Logo
          pw.Container(
            width: 90,
            height: 90,
            alignment: pw.Alignment.topCenter,
            child: logoImage != null
                ? pw.Image(logoImage, fit: pw.BoxFit.contain)
                : pw.SizedBox(),
          ),

          pw.SizedBox(width: 18),

          // Right Section
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text("EXPENSE REPORT", style: titleStyle),

                pw.SizedBox(height: 2),

                pw.Text("Fleet Management System", style: subtitleStyle),

                pw.SizedBox(height: 8),

                pw.Container(height: 1, color: PdfColor.fromHex("#2E7D32")),

                pw.SizedBox(height: 8),

                pw.Text(
                  profile.companyName,
                  style: companyStyle,
                ),

                if (profile.address != null && profile.address!.isNotEmpty) ...[
                  pw.SizedBox(height: 3),
                  pw.Text(
                    '${profile.address!}${profile.city != null ? ', ${profile.city!}' : ''}${profile.state != null ? ', ${profile.state!}' : ''}${profile.pincode != null ? ' - ${profile.pincode!}' : ''}',
                    style: infoStyle,
                  ),
                ],

                if (profile.phone != null && profile.phone!.isNotEmpty) ...[
                  pw.SizedBox(height: 2),
                  pw.Text(profile.phone!, style: infoStyle),
                ],

                if (profile.email != null && profile.email!.isNotEmpty) ...[
                  pw.SizedBox(height: 2),
                  pw.Text(profile.email!, style: infoStyle),
                ],

                if (profile.website != null && profile.website!.isNotEmpty) ...[
                  pw.SizedBox(height: 2),
                  pw.Text(profile.website!, style: infoStyle),
                ],
                
                if (profile.gstNumber != null && profile.gstNumber!.isNotEmpty) ...[
                  pw.SizedBox(height: 2),
                  pw.Text("GST: ${profile.gstNumber}", style: infoStyle),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildReportDetailsSection({
    required String truckFilter,
    required DateTime? fromDate,
    required DateTime? toDate,
    required String generatedOn,
    required DateFormat dateFormat,
    required pw.Font? unicodeFont,
  }) {
    final labelStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 9,
      fontWeight: pw.FontWeight.bold,
      color: PdfColor.fromInt(0xFF2E7D32),
    );
    final valueStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 9,
      color: PdfColors.grey800,
    );

    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(width: 0.6, color: PdfColor.fromInt(0xFFD6D6D6)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('REPORT DETAILS', style: labelStyle),
          pw.SizedBox(height: 8),
          pw.Row(
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Truck Number', style: labelStyle),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      truckFilter == 'All Trucks' ? 'All Trucks' : truckFilter,
                      style: valueStyle,
                    ),
                  ],
                ),
              ),
              pw.SizedBox(width: 12),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('From Date', style: labelStyle),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      fromDate == null ? '-' : dateFormat.format(fromDate),
                      style: valueStyle,
                    ),
                  ],
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('To Date', style: labelStyle),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      toDate == null ? '-' : dateFormat.format(toDate),
                      style: valueStyle,
                    ),
                  ],
                ),
              ),
              pw.SizedBox(width: 12),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Generated On', style: labelStyle),
                    pw.SizedBox(height: 3),
                    pw.Text(generatedOn, style: valueStyle),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSummarySection({
    required int totalEntries,
    required double totalAmount,
    required pw.Font? unicodeFont,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(width: 0.6, color: PdfColor.fromInt(0xFFD6D6D6)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'SUMMARY',
            style: pw.TextStyle(
              font: unicodeFont,
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromInt(0xFF2E7D32),
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Total Entries: $totalEntries',
                style: pw.TextStyle(
                  font: unicodeFont,
                  fontSize: 10,
                  color: PdfColors.grey800,
                ),
              ),
              pw.Text(
                'Total Expense: ${_formatCurrency(totalAmount)}',
                style: pw.TextStyle(
                  font: unicodeFont,
                  fontSize: 10,
                  color: PdfColors.grey800,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildGrandTotalRow({
    required double totalAmount,
    required pw.Font? unicodeFont,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: pw.BoxDecoration(color: PdfColor.fromInt(0xFF2E7D32)),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'GRAND TOTAL',
            style: pw.TextStyle(
              font: unicodeFont,
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
          ),
          pw.Text(
            _formatCurrency(totalAmount),
            style: pw.TextStyle(
              font: unicodeFont,
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildExpenseTable(
    List<Map<String, dynamic>> expenses,
    DateFormat dateFormat,
    pw.Font? unicodeFont,
  ) {
    final headers = [
      'Date',
      'Truck Number',
      'Driver',
      'Expense',
      'Paid By',
      'Payment Mode',
      'Amount',
    ];

    final data = expenses.map((expense) {
      return [
        _formatDate(expense['date']?.toString() ?? '', dateFormat),
        expense['truck_no']?.toString() ?? '',
        expense['driver_name']?.toString() ?? '',
        expense['expense_name']?.toString() ?? '',
        expense['paid_by']?.toString() ?? '',
        expense['payment_mode']?.toString() ?? '',
        _formatCurrency(_parseAmount(expense['amount'])),
      ];
    }).toList();

    final headerStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 8,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.white,
    );
    final baseTextStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 8,
      color: PdfColors.grey800,
    );
    final amountStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 8,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.grey800,
    );

    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(width: 0.6, color: PdfColor.fromInt(0xFFD6D6D6)),
      ),
      child: pw.Table(
        border: pw.TableBorder(
          horizontalInside: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
          verticalInside: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
          left: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
          top: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
          right: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
          bottom: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
        ),
        columnWidths: {
          0: const pw.FlexColumnWidth(1.0),
          1: const pw.FlexColumnWidth(0.85),
          2: const pw.FlexColumnWidth(1.0),
          3: const pw.FlexColumnWidth(1.0),
          4: const pw.FlexColumnWidth(0.9),
          5: const pw.FlexColumnWidth(0.9),
          6: const pw.FlexColumnWidth(0.9),
        },
        children: [
          pw.TableRow(
            decoration: const pw.BoxDecoration(
              color: PdfColor.fromInt(0xFF2E7D32),
            ),
            children: headers.map((header) {
              return pw.Container(
                padding: const pw.EdgeInsets.all(8),
                child: pw.Center(
                  child: pw.Text(
                    header,
                    style: headerStyle,
                    softWrap: false,
                    textAlign: pw.TextAlign.center,
                  ),
                ),
              );
            }).toList(),
          ),
          ...data.asMap().entries.map((entry) {
            final rowIndex = entry.key;
            final rowData = entry.value;
            return pw.TableRow(
              decoration: rowIndex.isEven
                  ? const pw.BoxDecoration(color: PdfColors.white)
                  : const pw.BoxDecoration(color: PdfColor.fromInt(0xFFF8F8F8)),
              children: rowData.asMap().entries.map((cellEntry) {
                final isAmount = cellEntry.key == rowData.length - 1;
                final value = cellEntry.value.toString();
                return pw.Container(
                  padding: const pw.EdgeInsets.all(8),
                  child: pw.Text(
                    value,
                    style: isAmount ? amountStyle : baseTextStyle,
                    softWrap: false,
                    textAlign: isAmount
                        ? pw.TextAlign.right
                        : pw.TextAlign.left,
                  ),
                );
              }).toList(),
            );
          }),
        ],
      ),
    );
  }

  static String _formatDate(String input, DateFormat formatter) {
    final parsed = DateTime.tryParse(input);
    if (parsed != null) return formatter.format(parsed);

    final parts = input.split('/');
    if (parts.length == 3) {
      final day = int.tryParse(parts[0]);
      final month = int.tryParse(parts[1]);
      final year = int.tryParse(parts[2]);
      if (day != null && month != null && year != null) {
        return formatter.format(DateTime(year, month, day));
      }
    }

    return input;
  }

  static String _formatCurrency(double amount) {
    final formatter = NumberFormat('#,##0.00', 'en_US');
    return '₹ ${formatter.format(amount)}';
  }

  static Future<pw.MemoryImage?> _loadLogoImage(String? customPath) async {
    try {
      if (customPath != null && customPath.isNotEmpty) {
        final file = File(customPath);
        if (await file.exists()) {
          final bytes = await file.readAsBytes();
          return pw.MemoryImage(bytes);
        }
      }
      final bytes = await rootBundle.load('assets/image/gpi_logo.png');
      return pw.MemoryImage(bytes.buffer.asUint8List());
    } catch (_) {
      return null;
    }
  }

  static Future<pw.Font?> _loadUnicodeFont() async {
    final candidates = <String>[
      r'C:\Windows\Fonts\arial.ttf',
      r'C:\Windows\Fonts\arialuni.ttf',
      r'C:\Windows\Fonts\seguiemj.ttf',
    ];

    for (final path in candidates) {
      final file = File(path);
      if (!await file.exists()) continue;

      try {
        final bytes = await file.readAsBytes();
        return pw.Font.ttf(bytes.buffer.asByteData());
      } catch (_) {
        continue;
      }
    }

    return null;
  }

  static double _parseAmount(dynamic value) {
    if (value is num) return value.toDouble();
    if (value is String) return double.tryParse(value) ?? 0.0;
    return 0.0;
  }
}
