import 'dart:io';

import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  PdfService._();

  static Future<void> generateExpenseReport({
    required List<Map<String, dynamic>> expenses,
    required String truckFilter,
    DateTime? fromDate,
    DateTime? toDate,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('yyyy-MM-dd');
    final dateTimeFormat = DateFormat('yyyy-MM-dd HH:mm');
    final unicodeFont = await _loadUnicodeFont();
    final totalAmount = expenses.fold<double>(
      0,
      (sum, expense) => sum + _parseAmount(expense['amount']),
    );
    final generatedOn = dateTimeFormat.format(DateTime.now());
    final logoImage = await _loadLogoImage();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(18),
        build: (pw.Context context) {
          return [
            _buildHeader(logoImage, unicodeFont),
            pw.SizedBox(height: 12),

            pw.SizedBox(height: 14),
            _buildReportDetailsSection(
              truckFilter: truckFilter,
              fromDate: fromDate,
              toDate: toDate,
              generatedOn: generatedOn,
              dateFormat: dateFormat,
              unicodeFont: unicodeFont,
            ),
            pw.SizedBox(height: 12),
            _buildSummarySection(
              totalEntries: expenses.length,
              totalAmount: totalAmount,
              unicodeFont: unicodeFont,
            ),
            pw.SizedBox(height: 12),
            expenses.isEmpty
                ? pw.Center(
                    child: pw.Text(
                      'No expense records found.',
                      style: pw.TextStyle(font: unicodeFont, fontSize: 12),
                    ),
                  )
                : _buildExpenseTable(expenses, dateFormat, unicodeFont),
            pw.SizedBox(height: 12),
            _buildGrandTotalRow(
              totalAmount: totalAmount,
              unicodeFont: unicodeFont,
            ),
          ];
        },
        footer: (pw.Context context) {
          return pw.Container(
            margin: const pw.EdgeInsets.only(top: 8),
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                top: pw.BorderSide(
                  color: PdfColor.fromInt(0xFFD6D6D6),
                  width: 0.6,
                ),
              ),
            ),
            padding: const pw.EdgeInsets.only(top: 6),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'Generated by',
                      style: pw.TextStyle(
                        font: unicodeFont,
                        fontSize: 8,
                        color: PdfColors.grey700,
                      ),
                    ),
                    pw.Text(
                      'Gautam Parkash India Private Limited',
                      style: pw.TextStyle(
                        font: unicodeFont,
                        fontSize: 8,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ),
                pw.Text(
                  generatedOn,
                  style: pw.TextStyle(
                    font: unicodeFont,
                    fontSize: 8,
                    color: PdfColors.grey700,
                  ),
                ),
                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: pw.TextStyle(
                    font: unicodeFont,
                    fontSize: 8,
                    color: PdfColors.grey700,
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (format) async => pdf.save());
  }

  static pw.Widget _buildHeader(
    pw.MemoryImage? logoImage,
    pw.Font? unicodeFont,
  ) {
    final titleStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 22,
      fontWeight: pw.FontWeight.bold,
      color: PdfColor.fromHex("#2E7D32"),
    );

    final subtitleStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 11,
      color: PdfColors.grey700,
    );

    final companyStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 10,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.black,
    );

    final infoStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 9,
      color: PdfColors.grey700,
    );

    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Logo
          pw.Container(
            width: 90,
            height: 90,
            alignment: pw.Alignment.topCenter,
            child: logoImage != null
                ? pw.Image(logoImage, fit: pw.BoxFit.contain)
                : pw.SizedBox(),
          ),

          pw.SizedBox(width: 18),

          // Right Section
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text("EXPENSE REPORT", style: titleStyle),

                pw.SizedBox(height: 2),

                pw.Text("Fleet Management System", style: subtitleStyle),

                pw.SizedBox(height: 8),

                pw.Container(height: 1, color: PdfColor.fromHex("#2E7D32")),

                pw.SizedBox(height: 8),

                pw.Text(
                  "Gautam Parkash India Private Limited",
                  style: companyStyle,
                ),

                pw.SizedBox(height: 3),

                pw.Text(
                  "60/128, Laxman Vihar, Muzaffarnagar - 251001",
                  style: infoStyle,
                ),

                pw.SizedBox(height: 2),

                pw.Text("+91 9760811758", style: infoStyle),

                pw.SizedBox(height: 2),

                pw.Text("gautamparkashindia@gmail.com", style: infoStyle),

                pw.SizedBox(height: 2),

                pw.Text("www.gautamparkashindia.com", style: infoStyle),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildReportDetailsSection({
    required String truckFilter,
    required DateTime? fromDate,
    required DateTime? toDate,
    required String generatedOn,
    required DateFormat dateFormat,
    required pw.Font? unicodeFont,
  }) {
    final labelStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 9,
      fontWeight: pw.FontWeight.bold,
      color: PdfColor.fromInt(0xFF2E7D32),
    );
    final valueStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 9,
      color: PdfColors.grey800,
    );

    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(width: 0.6, color: PdfColor.fromInt(0xFFD6D6D6)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('REPORT DETAILS', style: labelStyle),
          pw.SizedBox(height: 8),
          pw.Row(
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Truck Number', style: labelStyle),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      truckFilter == 'All Trucks' ? 'All Trucks' : truckFilter,
                      style: valueStyle,
                    ),
                  ],
                ),
              ),
              pw.SizedBox(width: 12),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('From Date', style: labelStyle),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      fromDate == null ? '-' : dateFormat.format(fromDate),
                      style: valueStyle,
                    ),
                  ],
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('To Date', style: labelStyle),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      toDate == null ? '-' : dateFormat.format(toDate),
                      style: valueStyle,
                    ),
                  ],
                ),
              ),
              pw.SizedBox(width: 12),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Generated On', style: labelStyle),
                    pw.SizedBox(height: 3),
                    pw.Text(generatedOn, style: valueStyle),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSummarySection({
    required int totalEntries,
    required double totalAmount,
    required pw.Font? unicodeFont,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(width: 0.6, color: PdfColor.fromInt(0xFFD6D6D6)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'SUMMARY',
            style: pw.TextStyle(
              font: unicodeFont,
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromInt(0xFF2E7D32),
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Total Entries: $totalEntries',
                style: pw.TextStyle(
                  font: unicodeFont,
                  fontSize: 10,
                  color: PdfColors.grey800,
                ),
              ),
              pw.Text(
                'Total Expense: ${_formatCurrency(totalAmount)}',
                style: pw.TextStyle(
                  font: unicodeFont,
                  fontSize: 10,
                  color: PdfColors.grey800,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildGrandTotalRow({
    required double totalAmount,
    required pw.Font? unicodeFont,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: pw.BoxDecoration(color: PdfColor.fromInt(0xFF2E7D32)),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'GRAND TOTAL',
            style: pw.TextStyle(
              font: unicodeFont,
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
          ),
          pw.Text(
            _formatCurrency(totalAmount),
            style: pw.TextStyle(
              font: unicodeFont,
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildExpenseTable(
    List<Map<String, dynamic>> expenses,
    DateFormat dateFormat,
    pw.Font? unicodeFont,
  ) {
    final headers = [
      'Date',
      'Truck Number',
      'Driver',
      'Expense',
      'Paid By',
      'Payment Mode',
      'Amount',
    ];

    final data = expenses.map((expense) {
      return [
        _formatDate(expense['date']?.toString() ?? '', dateFormat),
        expense['truck_no']?.toString() ?? '',
        expense['driver_name']?.toString() ?? '',
        expense['expense_name']?.toString() ?? '',
        expense['paid_by']?.toString() ?? '',
        expense['payment_mode']?.toString() ?? '',
        _formatCurrency(_parseAmount(expense['amount'])),
      ];
    }).toList();

    final headerStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 8,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.white,
    );
    final baseTextStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 8,
      color: PdfColors.grey800,
    );
    final amountStyle = pw.TextStyle(
      font: unicodeFont,
      fontSize: 8,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.grey800,
    );

    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(width: 0.6, color: PdfColor.fromInt(0xFFD6D6D6)),
      ),
      child: pw.Table(
        border: pw.TableBorder(
          horizontalInside: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
          verticalInside: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
          left: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
          top: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
          right: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
          bottom: const pw.BorderSide(
            width: 0.5,
            color: PdfColor.fromInt(0xFFD6D6D6),
          ),
        ),
        columnWidths: {
          0: const pw.FlexColumnWidth(1.0),
          1: const pw.FlexColumnWidth(0.85),
          2: const pw.FlexColumnWidth(1.0),
          3: const pw.FlexColumnWidth(1.0),
          4: const pw.FlexColumnWidth(0.9),
          5: const pw.FlexColumnWidth(0.9),
          6: const pw.FlexColumnWidth(0.9),
        },
        children: [
          pw.TableRow(
            decoration: const pw.BoxDecoration(
              color: PdfColor.fromInt(0xFF2E7D32),
            ),
            children: headers.map((header) {
              return pw.Container(
                padding: const pw.EdgeInsets.all(8),
                child: pw.Center(
                  child: pw.Text(
                    header,
                    style: headerStyle,
                    softWrap: false,
                    textAlign: pw.TextAlign.center,
                  ),
                ),
              );
            }).toList(),
          ),
          ...data.asMap().entries.map((entry) {
            final rowIndex = entry.key;
            final rowData = entry.value;
            return pw.TableRow(
              decoration: rowIndex.isEven
                  ? const pw.BoxDecoration(color: PdfColors.white)
                  : const pw.BoxDecoration(color: PdfColor.fromInt(0xFFF8F8F8)),
              children: rowData.asMap().entries.map((cellEntry) {
                final isAmount = cellEntry.key == rowData.length - 1;
                final value = cellEntry.value.toString();
                return pw.Container(
                  padding: const pw.EdgeInsets.all(8),
                  child: pw.Text(
                    value,
                    style: isAmount ? amountStyle : baseTextStyle,
                    softWrap: false,
                    textAlign: isAmount
                        ? pw.TextAlign.right
                        : pw.TextAlign.left,
                  ),
                );
              }).toList(),
            );
          }),
        ],
      ),
    );
  }

  static String _formatDate(String input, DateFormat formatter) {
    final parsed = DateTime.tryParse(input);
    if (parsed != null) return formatter.format(parsed);

    final parts = input.split('/');
    if (parts.length == 3) {
      final day = int.tryParse(parts[0]);
      final month = int.tryParse(parts[1]);
      final year = int.tryParse(parts[2]);
      if (day != null && month != null && year != null) {
        return formatter.format(DateTime(year, month, day));
      }
    }

    return input;
  }

  static String _formatCurrency(double amount) {
    final formatter = NumberFormat('#,##0.00', 'en_US');
    return '₹ ${formatter.format(amount)}';
  }

  static Future<pw.MemoryImage?> _loadLogoImage() async {
    try {
      final bytes = await rootBundle.load('assets/image/gpi_logo.png');
      return pw.MemoryImage(bytes.buffer.asUint8List());
    } catch (_) {
      return null;
    }
  }

  static Future<pw.Font?> _loadUnicodeFont() async {
    final candidates = <String>[
      r'C:\Windows\Fonts\arial.ttf',
      r'C:\Windows\Fonts\arialuni.ttf',
      r'C:\Windows\Fonts\seguiemj.ttf',
    ];

    for (final path in candidates) {
      final file = File(path);
      if (!await file.exists()) continue;

      try {
        final bytes = await file.readAsBytes();
        return pw.Font.ttf(bytes.buffer.asByteData());
      } catch (_) {
        continue;
      }
    }

    return null;
  }

  static double _parseAmount(dynamic value) {
    if (value is num) return value.toDouble();
    if (value is String) return double.tryParse(value) ?? 0.0;
    return 0.0;
  }
}
