import '../database/database_helper.dart';
import '../models/truck.dart';

class TruckService {
  TruckService._();

  static final TruckService instance = TruckService._();

  Future<int> addTruck(Truck truck) async {
    final now = DateTime.now().toIso8601String();
    final data = truck.toMap();
    data['created_at'] = now;
    data['updated_at'] = now;
    data.remove('id'); // Ensure ID is generated by DB
    return await DatabaseHelper.instance.insertTruck(data);
  }

  Future<int> updateTruck(Truck truck) async {
    if (truck.id == null) throw Exception('Truck ID is required for update');
    final data = truck.toMap();
    data['updated_at'] = DateTime.now().toIso8601String();
    data.remove('id');
    data.remove('created_at'); // Don't overwrite created_at
    return await DatabaseHelper.instance.updateTruckRecord(truck.id!, data);
  }

  Future<int> deleteTruck(int id) async {
    return await DatabaseHelper.instance.deleteTruckRecord(id);
  }

  Future<Truck?> getTruck(int id) async {
    final data = await DatabaseHelper.instance.queryTruck(id);
    return data != null ? Truck.fromMap(data) : null;
  }

  Future<List<Truck>> getAllTrucks() async {
    final data = await DatabaseHelper.instance.queryAllTrucks();
    return data.map((m) => Truck.fromMap(m)).toList();
  }

  Future<List<Truck>> getActiveTrucks() async {
    final data = await DatabaseHelper.instance.queryActiveTrucks();
    return data.map((m) => Truck.fromMap(m)).toList();
  }

  Future<List<Truck>> searchTrucks(String query) async {
    final data = await DatabaseHelper.instance.querySearchTrucks(query);
    return data.map((m) => Truck.fromMap(m)).toList();
  }
}
